# Generated by Django 4.1.4 on 2022-12-29 14:27

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PostBoard', '0002_alter_comment_time_in_alter_post_time_in'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='time_in',
            field=models.DateTimeField(default=datetime.datetime(2022, 12, 29, 14, 27, 4, 904552)),
        ),
        migrations.AlterField(
            model_name='post',
            name='time_in',
            field=models.DateTimeField(verbose_name=datetime.datetime(2022, 12, 29, 14, 27, 4, 904552)),
        ),
    ]
