# Generated by Django 4.1.4 on 2023-01-18 03:10

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('PostBoard', '0011_alter_comment_time_in_alter_post_time_in_like'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='like',
            name='post',
        ),
        migrations.AddField(
            model_name='like',
            name='comment',
            field=models.ForeignKey(default=False, on_delete=django.db.models.deletion.CASCADE, to='PostBoard.comment'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='time_in',
            field=models.DateTimeField(default=datetime.datetime(2023, 1, 18, 3, 10, 12, 659211)),
        ),
        migrations.AlterField(
            model_name='post',
            name='time_in',
            field=models.DateTimeField(default=datetime.datetime(2023, 1, 18, 3, 10, 12, 643586)),
        ),
    ]
