# Generated by Django 4.1.4 on 2023-01-18 08:07

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PostBoard', '0013_alter_comment_time_in_alter_like_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='time_in',
            field=models.DateTimeField(default=datetime.datetime(2023, 1, 18, 8, 7, 48, 612859, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='post',
            name='time_in',
            field=models.DateTimeField(default=datetime.datetime(2023, 1, 18, 8, 7, 48, 612859, tzinfo=datetime.timezone.utc)),
        ),
    ]
