# Generated by Django 4.1.4 on 2023-01-18 08:57

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PostBoard', '0014_alter_comment_time_in_alter_post_time_in'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='cover',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='comment',
            name='time_in',
            field=models.DateTimeField(default=datetime.datetime(2023, 1, 18, 8, 57, 0, 226489, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='post',
            name='time_in',
            field=models.DateTimeField(default=datetime.datetime(2023, 1, 18, 8, 57, 0, 210866, tzinfo=datetime.timezone.utc)),
        ),
    ]
